baseURL = "https://你的用户名.github.io/"
languageCode = "zh-cn"
title = "Autumn"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # 自动切换夜间模式
    showReadingTime = true
    displayFullContent = false
    ShowPostNavLinks = true
	[params.profileMode]
    enabled = true # 开启个人模式
    title = "Autumn" # 首页大标题
    subtitle = "夜深忽梦少年事，梦啼妆泪红阑干。" # 你的谏言/座右铭
    displayFullContent = false
    imageUrl = "avatar.jpg" # 头像路径
    imageWidth = 120 # 头像大小
    imageHeight = 120
	[[params.profileMode.buttons]]
        name = "开始阅读"
        url = "posts"

    